name: sw_zad2

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image to DockerHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      security-events: write

    steps:
      -
        name: Check out the source_repo
        uses: actions/checkout@v4

      -
        name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ vars.GITHUB_USERNAME }}/sw_lab2
          flavor: latest=false
          labels:
          org.opencontainers.image.source="https://github.com/${{ vars.GITHUB_USERNAME }}/sw_lab2"
          tags: |
            type=edge,branch=$repo.default_branch
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}


      -
        name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      -
        name: Buildx set-up
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ vars.GITHUB_USERNAME }}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true
          push: true
          cache-from: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/sw_zad2:cache
          cache-to: |
            type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/sw_zad2:cache
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
      - name: Push Docker Image
          if: success()
          run: |
              docker buildx imagetools create --tag ghcr.io/${{ vars.GITHUB_USERNAME }}/last-image:latest  ${{ steps.meta.outputs.tags }}
